### ISSUE TITLE
author的amap非常实用,放大地图偶遇crash,请求指点一二

### ISSUE THREAD

**Issue by MicroKibaco** [dianwoba/react-native-amap#20]
## 使用react-native-amap
 库文件 遇到这样子的crash情况 请求author 略加指点
> FATAL EXCEPTION: main
                                                                           Process: com.asiainfo.channelmanager, PID: 7994
                                                                           java.lang.AssertionError: Dispatched event hasn't been initialized
                                                                               at com.facebook.infer.annotation.Assertions.assertCondition(Assertions.java:65)
                                                                               at com.facebook.react.uimanager.events.EventDispatcher.dispatchEvent(EventDispatcher.java:115)
                                                                               at com.dianwoba.rctamap.AMapView$9.run(AMapView.java:526)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by marshalYuan** [comment]
你是在RN哪个版本下使用这个的啊

**Comment by MicroKibaco** [comment]
0.37+
